//NOTIFICATION
export const PUSH_NOTIFICATION = 'PUSH_NOTIFICATION';
export const SHIFT_NOTIFICATION = 'SHIFT_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';
export const CLEAR_NOTIFICATIONS = 'CLEAR_NOTIFICATIONS';

// USER POST
export const SET_USER_POSTS = 'SET_USER_POSTS';
